import { useEffect, useState } from 'react'; import { api } from '@shared/api/client'; import { LoadingSpinner } from '@shared/components/LoadingSpinner'; import type { Event } from '@shared/types';
export function EventManagePage() {
  const [events, setEvents] = useState<Event[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  const fetch = async () => { setLoading(true); try { const r = await api<{ events: Event[]; total_count: number }>(`/admin/events?page=\${page}&limit=5`); setEvents(r.events || []); setTotal(r.total_count || 0); } catch {} finally { setLoading(false); } };
  useEffect(() => { fetch(); }, [page]);
  const del = async (e: Event) => { if (!confirm(e.title + ' を削除しますか？')) return; await api('/admin/events/' + e.id, { method: 'DELETE' }); fetch(); };
  const fmt = (d: string | null) => d ? new Date(d).toLocaleDateString('ja-JP') : '-';
  return (<div><h1 className="text-2xl font-bold mb-4">イベント管理</h1>{loading ? <LoadingSpinner /> : (<div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50"><th className="text-left px-4 py-2">タイトル</th><th className="text-left px-4 py-2">作成者</th><th className="text-left px-4 py-2">期限</th><th className="text-left px-4 py-2">ステータス</th><th className="text-left px-4 py-2">操作</th></tr></thead><tbody>{events.map((e) => (<tr key={e.id} className="border-b last:border-0"><td className="px-4 py-2 font-medium">{e.title}</td><td className="px-4 py-2 text-gray-500">{e.creator?.name || '-'}</td><td className="px-4 py-2 text-gray-500">{fmt(e.deadline)}</td><td className="px-4 py-2"><span className={`text-xs px-1.5 py-0.5 rounded \${e.status === 'active' ? 'bg-blue-100 text-blue-700' : e.status === 'cancelled' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-600'}`}>{e.status === 'active' ? '募集中' : e.status === 'cancelled' ? '中止' : '終了'}</span></td><td className="px-4 py-2"><button onClick={() => del(e)} className="text-xs text-red-600 hover:underline">削除</button></td></tr>))}</tbody></table>{total > 5 && (<div className="flex justify-center gap-2 p-4"><button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page <= 1} className="px-3 py-1 bg-gray-200 rounded text-sm disabled:opacity-50">前へ</button><span className="px-3 py-1 text-sm text-gray-600">{page} / {Math.ceil(total / 5)}</span><button onClick={() => setPage((p) => p + 1)} disabled={page * 5 >= total} className="px-3 py-1 bg-gray-200 rounded text-sm disabled:opacity-50">次へ</button></div>)}</div>)}</div>);
}
